//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRpcClient.MathService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Math", Namespace="http://schemas.datacontract.org/2004/07/XmlRpcWebService")]
    [System.SerializableAttribute()]
    public partial class Math : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Number1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Number2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number1 {
            get {
                return this.Number1Field;
            }
            set {
                if ((this.Number1Field.Equals(value) != true)) {
                    this.Number1Field = value;
                    this.RaisePropertyChanged("Number1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number2 {
            get {
                return this.Number2Field;
            }
            set {
                if ((this.Number2Field.Equals(value) != true)) {
                    this.Number2Field = value;
                    this.RaisePropertyChanged("Number2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathService.IMaths")]
    public interface IMaths {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaths/Addition", ReplyAction="http://tempuri.org/IMaths/AdditionResponse")]
        int Addition(XmlRpcClient.MathService.Math obj1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaths/Addition", ReplyAction="http://tempuri.org/IMaths/AdditionResponse")]
        System.Threading.Tasks.Task<int> AdditionAsync(XmlRpcClient.MathService.Math obj1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaths/Subtraction", ReplyAction="http://tempuri.org/IMaths/SubtractionResponse")]
        int Subtraction(XmlRpcClient.MathService.Math obj1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaths/Subtraction", ReplyAction="http://tempuri.org/IMaths/SubtractionResponse")]
        System.Threading.Tasks.Task<int> SubtractionAsync(XmlRpcClient.MathService.Math obj1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathsChannel : XmlRpcClient.MathService.IMaths, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathsClient : System.ServiceModel.ClientBase<XmlRpcClient.MathService.IMaths>, XmlRpcClient.MathService.IMaths {
        
        public MathsClient() {
        }
        
        public MathsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Addition(XmlRpcClient.MathService.Math obj1) {
            return base.Channel.Addition(obj1);
        }
        
        public System.Threading.Tasks.Task<int> AdditionAsync(XmlRpcClient.MathService.Math obj1) {
            return base.Channel.AdditionAsync(obj1);
        }
        
        public int Subtraction(XmlRpcClient.MathService.Math obj1) {
            return base.Channel.Subtraction(obj1);
        }
        
        public System.Threading.Tasks.Task<int> SubtractionAsync(XmlRpcClient.MathService.Math obj1) {
            return base.Channel.SubtractionAsync(obj1);
        }
    }
}
